### ISSUE TITLE
JOIN on NR

### ISSUE THREAD

**Issue by peheje** [mechatroner/RBQL#10]
I would like to join two tables on the their NR column.

`select * join <filepath> ON aNR == bNR` does not work I get error:

> Invalid join syntax. Must be: `"<JOIN> /path/to/B/table on a<i> == b<j>"`

**Comment by mechatroner** [comment]
I like the idea. For some reason I never though about this myself.
I think this can be implemented as "SequentialMap" which would be more efficient than standard "HashJoinMap" and would avoid keeping the join B table in memory.

**Comment by mechatroner** [comment]
Join on NR is now supported in the master branch. But it will take some time to release it to the apps.
Current implementation is not optimal: it uses the default HashJoinMap, instead of SequentialMap.
