### ISSUE TITLE
Can you have some example how to use as a library

### ISSUE THREAD

**Issue by trungbanh** [mechatroner/RBQL#16]
how i can use like 
```python 
import RBQL  as rbdb

rbdb.query("select * where .... ")
```
if can use it as function it must help for my data process

**Comment by mechatroner** [comment]
Hi @trungbanh !
There are 2 simple examples thow to use RBQL as a library:
https://github.com/mechatroner/RBQL/blob/master/test/library_demos/table_test.py
and
https://github.com/mechatroner/RBQL/blob/master/test/library_demos/csv_test.py
Also you can use this documentation: https://github.com/mechatroner/rbql-py/blob/master/LIBRARY.md

And be prepared that RBQL generates a disposable python module for each query, so running queries with very high frequency (e.g. more than one query per second) is not recommended.
Good luck and please let me know if you have other questions!

**Comment by trungbanh** [comment]
> Hi @trungbanh !
> There are 2 simple examples thow to use RBQL as a library:
> https://github.com/mechatroner/RBQL/blob/master/test/library_demos/table_test.py
> and
> https://github.com/mechatroner/RBQL/blob/master/test/library_demos/csv_test.py
> Also you can use this documentation: https://github.com/mechatroner/rbql-py/blob/master/LIBRARY.md
> 
> And be prepared that RBQL generates a disposable python module for each query, so running queries with very high frequency (e.g. more than one query per second) is not recommended.
> Good luck and please let me know if you have other questions!

**mechatroner**  thank you

**Comment by mechatroner** [comment]
I've changed API in version 0.11: 
* Renamed main functions as `csv_run ->query_csv`, `table_run -> query_table` and `generic_run -> query`
* In the new version query functions do not return error objects, instead they throw exceptions ( this is a more Pythonic way of error handling )
* In the new version query functions do not return warnings, instead library user has to pass empty list where warnings will be stored.

I also updated documentation and example code
