### ISSUE TITLE
support 'AS' keyword as a way to name the output columns

### ISSUE THREAD

**Issue by mechatroner** [mechatroner/RBQL#29]
[AS in SQL: definition](https://www.w3schools.com/sql/sql_ref_as.asp)
It would be very convenient for CSV and Parquet(if we start to support it).

Although `AS` wouldn't make sense for some of the output formats e.g. for json (if we start to support it at some point). It could be possible to treat `AS` in json output as a way to create key-value dictionary pairs, but it is actually much easier to do through the native json syntax e.g. instead of `SELECT a['foo'] as 'bar'` write `SELECT {'foo': a['bar']}`, the later notation also provides much more flexibility. Also `AS` will not work well with native 2D-arrays as the output format.

**Comment by ankon** [comment]
I'm using RBQL (through VSCode) to "explore" CSV data produced as output by other scripts, and `AS` would help a lot with queries such as `SELECT a1,AVG(a2) GROUP BY a1` -- right now the second column just appears as `col2`. That's fine with just one column, but it gets annoying with many of them.

**Comment by mechatroner** [comment]
Done. 
Now it is possible to rewrite the query like this:  `SELECT a2 as id,AVG(a4) AS average GROUP BY a2`.
