### ISSUE TITLE
error in Node.js docu on www.npmjs.com

### ISSUE THREAD

**Issue by GreyGooseVX** [mechatroner/RBQL#37]
Hello there,

in the docu on https://www.npmjs.com/package/rbql/v/0.25.0 there is a code snipped with the heading 'Example of query_csv() usage'.

In there, it says
```
const rbql_csv = require('rbql_csv')
[...]
rbql_csv.query_csv([...])
```

But trying this just gives me

> Error: Cannot find module 'rbql_csv'

I tested the following and it works, so perhaps edit this docu:
```
const rbql_csv = require('rbql_csv')
[...]
rbql_csv.query_csv([...])
```

BR
Tobias

**Comment by mechatroner** [comment]
Thank you for pointing this out!
The root cause actually is the completely wrong structure of the javascript package - it doesn't have neither "main" nor "browser" entries and the index.js file is also not there. I will need to figure out how to properly fix this.
